// Code generated by Kitex v0.7.1. DO NOT EDIT.

package user

import (
	"context"
	api "douyin/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *api.RegisterRequest, callOptions ...callopt.Option) (r *api.RegisterResponse, err error)
	Login(ctx context.Context, req *api.LoginRequest, callOptions ...callopt.Option) (r *api.LoginResponse, err error)
	Get(ctx context.Context, req *api.GetInfoRequest, callOptions ...callopt.Option) (r *api.GetInfoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserClient struct {
	*kClient
}

func (p *kUserClient) Register(ctx context.Context, req *api.RegisterRequest, callOptions ...callopt.Option) (r *api.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserClient) Login(ctx context.Context, req *api.LoginRequest, callOptions ...callopt.Option) (r *api.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserClient) Get(ctx context.Context, req *api.GetInfoRequest, callOptions ...callopt.Option) (r *api.GetInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx, req)
}
